### ISSUE TITLE
data no longer available for Guam?

### ISSUE THREAD

**Issue by craftj2** [NREL/developer.nrel.gov#109]
I had been using the NSRDB 9105 API download until recently, when I started receiving this message: 

"This API has been permanently taken out of service. Please use https://developer.nrel.gov/docs/solar/nsrdb/psm3_data_download/"

I have made the switch and its mostly working fine except for when I attempt to access data for Guam, which had been working with the old API. With the new one, I now receive the message:

"The 'wkt' parameter did not match any known data points."

For this request, the parameter is "wkt":"POINT(144.8 13.48333)"

This is the same wkt parameter I had been using for the old API. Is there a way, either through modifying my request or using a different API, that I can access the data for Guam and other US territories?

**Comment by GUI** [comment]
@PjEdwards: I think this might be a question for you.

**Comment by PjEdwards** [comment]
@craftj2 Yes, due to a combination of data inconsistencies and cost of maintenance, the APIs you used to use are no longer available via developer.nrel.gov. However the data can still be downloaded en masse. If you look at page 11 of [this document](https://www.nrel.gov/docs/fy07osti/41364.pdf) you can find references to a few different sources. However, it is also worth noting that this data is quite out of date. You might consider dropping a message to the NSRDB team [using this form](https://nsrdb.nrel.gov/contact) and asking if there is a more suitable and current dataset available depending on your needs?

**Comment by craftj2** [comment]
As I said, I've switched to the Physical Solar Model 3 API, which is functional. I just noticed that it doesn't seem to cover Guam, so I was wondering if that was a limitation of the PSM3 data and what other geographic limitations it may have compared to the NSRDB 9105 data.

**Comment by PjEdwards** [comment]
Gotcha. You can see the coverage of both datasets on the map at https://maps.nrel.gov/nsrdb-viewer/?aL=UdPEX9%255Bv%255D%3Dt%26f69KzE%255Bv%255D%3Dt%26f69KzE%255Bd%255D%3D1%26yTLDDF%255Bv%255D%3Dt%26yTLDDF%255Bd%255D%3D2&bL=clight&cE=0&lR=0&mC=4.740675384778373%2C22.8515625&zL=2

**Comment by reger** [comment]
@PjEdwards @craftj2 is this resolved/answered now? Can it be closed?

**Comment by PjEdwards** [comment]
Yes, plz close
