### ISSUE TITLE
migrate developer.nrel.gov fully to api.data.gov endpoints

### ISSUE THREAD

**Issue by gbinal** [NREL/developer.nrel.gov#14]
http://developer.nrel.gov points to its native endpoints instead of dogfooding api.data.gov, thus missing out on some resulting efficiences. Can we go ahead and make the jump?

**Comment by GUI** [comment]
@gbinal: Well, it was a looooooonnnnggg time coming, but as of today, developer.nrel.gov is now finally switched over and is using api.data.gov (this got wrapped up in a larger effort to move some of our API hosting out to the cloud, so that's why it took longer and got more complicated). The transition should have been seamless to our users since we're still using our own domain, but we're fully switched over to api.data.gov behind the scenes now. And as part of this, I've removed our duplicative docs from the api.data.gov site, and redirect people to our site: https://api.data.gov/docs/nrel/

We're all very excited at NREL to finally be onboard and get the api.data.gov benefits. Thanks for everything!! :tada: :balloon: :tada: :balloon: :tada:

**Comment by gbinal** [comment]
Heyyyy!!!! Congrats!  Welcome!
