### ISSUE TITLE
New to APIs/data scraping, can't get request

### ISSUE THREAD

**Issue by ctinman** [NREL/developer.nrel.gov#147]
Hello, new to APIs and currently trying to extract multiple hourly solar datasets from PVWatts. I've been hitting multiple errors and have been unable to retrieve data, and did not know where else to go for help.

Right now, I keep getting a 400 error message. I believe my parameters are sound, but I don't know exactly what the URL should be.

The code:

`
url = 'http://developer.nrel.gov/api/pvwatts/v6.format?parameters'
parameters = {       
        'format' : 'json',       
        'api_key' : '[API key]',       
        'system_capacity' : 50.0,       
        'module_type' : 0,       
        'losses' : 14.0,       
        'array_type' : 0,       
        'tilt' : 20,       
        'azimuth' : 180,
        'lat' : 47.648737,
        'lon' : -122.319889,
        'timeframe' : 'hourly'}
response = requests.get(url, params=parameters)
print(response)
`
Which produces:
`<Response 400>`

Any help would be greatly appreciated, thank you!

EDIT: Apologies for the terrible formatting

**Comment by GUI** [comment]
@ctinman: Have you inspected the body of the response? It should describe the error in more detail. But based on the 400 status code and URL, I'm guessing this might be due to the URL being requested with http, instead of https. We require https connections for API requests, so try updating your code to connect to `https://developer.nrel.gov` instead. Let us know if that's still not working, though.

**Comment by Sophieleamon** [comment]
the url should be: http://developer.nrel.gov/api/pvwatts/v6.**csv**? or http://developer.nrel.gov/api/pvwatts/v6.**json**?
depending on the format output you want. Hope this helps.
