### ISSUE TITLE
An error has occurred. Please consult with your administrator.

### ISSUE THREAD

**Issue by j0hnm4r5** [NREL/developer.nrel.gov#203]
We're getting an error when trying to load a page containing a fueling station locator:

`An error has occurred. Please consult with your administrator. Your support ID is:5730482191151852868`

**Comment by reger** [comment]
@j0hnm4r5 do you mean a page of yours where you've embedded it? Or the one on the AFDC itself?

**Comment by j0hnm4r5** [comment]
@reger sorry; a page we host ourselves, using the "Embed Tool" data from the afdc site:

```
<div id="afdc-stations"><div id="afdc-stations-loading">Loading alternative fueling station locator...</div></div><script type="text/javascript">window.afdcStationsOptions = {"country":"US","localeCountry":"US","path":"/find/nearest","query":{"fuel":["CNG, LNG"]}}</script><script async defer src="https://widgets.nrel.gov/afdc/station-locator/assets/embed.js"></script><noscript>Please enable JavaScript to view the alternative fueling station locator.</noscript>
```

**Comment by j0hnm4r5** [comment]
It seems to be working now! Did anything change on your end?

**Comment by j0hnm4r5** [comment]
Ah, scratch that; it's inconsistent.

**Comment by reger** [comment]
Okay, we'll look into it.

**Comment by GUI** [comment]
@j0hnm4r5: Is the link where this tool is embedded public? If it is and that's something you could share, that might help us see if we can reproduce the issue. Thanks!

**Comment by j0hnm4r5** [comment]
Of course! Thanks for helping.

https://ngvamerica.org/fuel/fuel/ngv-station-map

Occasionally it loads fine, but most of the the time it throws the above error. It'll look like the page loads indefinitely, but if you go into the console, it'll say `Uncaught SyntaxError: Unexpected token '<'`. And if you click the line number, it will point to some HTML that was injected into the bundle that mentions the error and support ID.

**Comment by GUI** [comment]
@j0hnm4r5: Sorry for the delay! So, our IT staff says that this is being blocked since the IP the request is coming from is flagged as a phishing IP. Now, I realize this is probably a false positive, but I am wondering if this maybe points to an issue with how the widget is being embedded on your site. I don't actually see our snippet code directly in your source code, particularly the `<script async defer src="https://widgets.nrel.gov/afdc/station-locator/assets/embed.js"></script>` line. It appears like perhaps something server-side is making this request to the javascript file, which I think is what's leading to this block. So I'm not entirely sure how all this is working, but are you doing something custom to embed the widget on the site? I'm not sure making a server-side request to our embed javascript code will work properly even if we address the IP block, unless it's un-cached (but it sort of looks like the results are being cached in https://ngvamerica.org/wp-content/cache/min/1/7fd8a897e2cae44407b2a4241cd30eb9.js).

Does that make sense or give you some ideas? We only really support directly embedding the widget using the source code provided on our page. But if you're needing to do something more custom, let us know how specifically you need it to work, and we can maybe try to figure something out.

**Comment by j0hnm4r5** [comment]
Interesting. We just moved the site from a self-hosted AWS instance, to one hosted by WPEngine (which I suppose could be hosting our site on a shared IP with other sites associated with Phishing).

The site is built in a WordPress page builder (Beaver Builder), which totally could be doing something with delaying the request. I inherited the site from our creative team, and unfortunately redoing it with actual code isn't in the cards right now. The following is embedded as an "HTML Block" within the page:

```html
<div id="afdc-stations">
	<div id="afdc-stations-loading">Loading alternative fueling station locator...</div>
</div>
<script
	type="text/javascript">window.afdcStationsOptions = { "country": "US", "localeCountry": "US", "path": "/find/nearest", "query": { "fuel": ["CNG, LNG"] } }</script>
<script async defer src="https://widgets.nrel.gov/afdc/station-locator/assets/embed.js"></script>
<noscript>Please enable JavaScript to view the alternative fueling station locator.</noscript>
```

The page does occasionally load okay on my machine (usually when I'm logged into the Wordpress admin, which I think skips the cache), and when it does, the source does contain that embed code in full.

If it helps, the embed was working perfectly fine before we moved to WPEngine, so whitelisting the IP might just solve the issue outright.

**Comment by j0hnm4r5** [comment]
Have you had a chance to whitelist the IP address yet (or is that even possible)?

**Comment by j0hnm4r5** [comment]
I figured out a workaround! Hitting the page with the query fragment already in the URL seems to trick everything into working.

[https://ngvamerica.org/fuel/ngv-station-map/?f#/find/nearest?fuel=CNG,%20LNG](https://ngvamerica.org/fuel/ngv-station-map/?f#/find/nearest?fuel=CNG,%20LNG)
