### ISSUE TITLE
Alternative Fuel Station API not returning results based on lat & lon

### ISSUE THREAD

**Issue by sfirke** [NREL/developer.nrel.gov#209]
Hello,

I'm trying to retrieve EV charging stations in the Ann Arbor, MI area.  I'm making an API query with that latitude and longitude, but am getting unrelated results, e.g., chargers in California.  My query is:
```
https://developer.nrel.gov/api/alt-fuel-stations/v1.csv?fuel_type=ELEC&latitude=42.277419&longitude=-83.749477&radius=10&limit=200&api_key=<myAPIkey>
```
Can you advise on how to retrieve just the stations within 10 miles of that lat/lon ?  I read the API documentation, sorry if I'm missing something obvious.  Thanks!

**Comment by kanderso-nrel** [comment]
Hi @sfirke I'm not familiar with the `alt-fuel-stations` api, but maybe you just need to edit the url to include `/nearest`, i.e. instead of `/api/alt-fuel-stations/v1`, use `/api/alt-fuel-stations/v1/nearest`?  See the different endpoints here:

https://developer.nrel.gov/docs/transportation/alt-fuel-stations-v1/
