### ISSUE TITLE
I am not getting dataset for some of the locations

### ISSUE THREAD

**Issue by manojdhiman** [NREL/developer.nrel.gov#21]
I am using this api to get the dataset to calculate the solar system performance . this is the api i am using 

`developer.nrel.gov/api/pvwatts/v5.json?api_key=***********************8&lat=56.26392&lon=9.50178500000004&system_capacity=4&azimuth=180&tilt=20&array_type=0&module_type=0&losses=12.32&inv_eff=96&dataset=intl&timeframe=hourly`

this is not working . response is 
`
{"inputs":{"lat":"56.26392","lon":"9.50178500000004","system_capacity":"4","azimuth":"180","tilt":"20","array_type":"0","module_type":"0","losses":"12.32","inv_eff":"96","dataset":"intl","timeframe":"hourly"},"errors":["No climate data found with dataset=intl for location specified: lat=56.26392 lon=9.50178500000004"],"warnings":[],"version":"1.2.0","ssc_info":{"version":45,"build":"Linux 64 bit GNU/C++ Jul  7 2015 14:24:09"},"outputs":{}}
`

while this url is showing me the data 

``
http://developer.nrel.gov/api/pvwatts/v5.json?api_key=*******************&lat=40.4167754&lon=-3.7037901999999576&system_capacity=4&azimuth=180&tilt=20&array_type=0&module_type=0&losses=12.32&inv_eff=96&dataset=intl&timeframe=hourly

``

**Comment by GUI** [comment]
@manojdhiman: We do not have international climate data available within the default radius (100 miles) of 56.26392, 9.501785. If you expand your `radius` parameter, we do have international data at the Copenhagen site about 140 miles away:

http://developer.nrel.gov/api/pvwatts/v5.json?api_key=DEMO_KEY&lat=56.26392&lon=9.50178500000004&radius=150&system_capacity=4&azimuth=180&tilt=20&array_type=0&module_type=0&losses=12.32&inv_eff=96&dataset=intl&timeframe=hourly

So you can try expanding your search radius if you hit this `No climate data found with dataset=intl for location specified` error.

You may also find the [Solar Data Query API](https://developer.nrel.gov/docs/solar/data-query-v1/) useful for determining the available climate datasets available for a given location. In the [example](https://developer.nrel.gov/docs/solar/data-query-v1/#examples) you can see how you can use this API to query a specific location with a radius and get back a complete list of datasets that have data for the given location. This can sometimes be handy to determine when you might need to switch the PVWatts `dataset` parameter between `tmy2`, `tmy3`, and `intl` if you're querying areas both in the US and internationally.

Let us know if you have any further questions.

@reger: Let me know if you have anything to add. But since this issue comes up from time-to-time about which dataset to use, how to find nearby locations, etc, do you think it might be worth expanding the PVWatts documentation in this area? I'm wondering if we could maybe expand our explanations of datasets and climate locations a bit, and perhaps some concrete examples of how you might use the solar data query API in conjunction with PVWatts would help. Let me know if you have any thoughts on this, and we could maybe open a separate issue for this, if you want.

**Comment by reger** [comment]
@GUI Even after the recent addition of international sites they aren't as numerous or dense as tmy2 and tmy3. Expanding search radius is one option, as is using the Solar Data Query API. You can also pass in `radius=0` to use the closest station, regardless of distance, as documented `http://developer.nrel.gov/docs/solar/pvwatts-v5/` We'd need to talk to the rest of the pvwatts team about additional documentation, examples, etc.

**Comment by manojdhiman** [comment]
for me now it is working after i add `radius=500` in my api callFor Us countries . But not for indian countries . is it possible to use for indian countries or not??

**Comment by reger** [comment]
I checked with solar data query and I get back results using Mumbai:  http://developer.nrel.gov/api/solar/data_query/v1.json?api_key=DEMO_KEY&address=mumbai&radius=50&all=1  What API call are you making where you aren't getting results with `radius=500`? And did you try `radius=0` for whatever location in India where you didn't get results?

**Comment by manojdhiman** [comment]
not worked for Shimla etc. working for Mumbai '

**Comment by reger** [comment]
What result do you get for Shimla?

**Comment by manojdhiman** [comment]
this is the result .I am using this on my localhost and my location is `india`. 

api url 

http://developer.nrel.gov/api/pvwatts/v5.json?api_key=yNaNoBgRZqzpyKfHfKm2iCS3xmmFGEG3iOlJ5iWi&radius=500&lat=31.1048145&lon=77.17340330000002&system_capacity=4&azimuth=180&tilt=20&array_type=1&module_type=0&losses=12.32&inv_eff=96&dataset=intl&timeframe=hourly

result 
`
{"inputs":{"radius":"500","lat":"31.1048145","lon":"77.17340330000002","system_capacity":"4","azimuth":"180","tilt":"20","array_type":"1","module_type":"0","losses":"12.32","inv_eff":"96","dataset":"intl","timeframe":"hourly"},"errors":["An internal error occurred in the pvwattsv5 module."],"warnings":[],"version":"1.2.0","ssc_info":{"version":45,"build":"Linux 64 bit GNU/C++ Jul  7 2015 14:24:09"},"outputs":{}}
`

**Comment by reger** [comment]
It looks like there's a problem in that climate file, sorry about that. You can use solar data query to find other options close by that might work. We are going to look into the issues with the climate file, but I can't give you a good estimate of when we'll be able to get things fixed.

**Comment by pravin174** [comment]
Hi,
I am trying to get data from solar resource api but i can't get any data for indian location. 
https://developer.nrel.gov/api/solar/solar_resource/v1.xml?api_key=DATA_API_KEY&lat=23&lon=72
please help me if you have any resolution.

**Comment by reger** [comment]
@pravin174 I don't believe we have data for non-US locations for the solar resource API.

**Comment by pravin174** [comment]
Hi Reger,
do i have to pass any extra params OR
do you have any lat long list for indian location. give me just 5-10 locations if possible.

**Comment by reger** [comment]
@pravin174 As far as I know, we don't have any data for Indian locations for that API, only US locations, so there are no locations I can give you in India which will return data for the solar resource API. The only API that I know of which we do have data for India is pvwatts.

**Comment by Juantxor** [comment]
I'm using radius=0 and still some locations are not working:
In kuwait I can not make it work. Please help!

http://developer.nrel.gov/api/pvwatts/v5.json?api_key=cZ8JyiA7MgLuShVAltjcxeemrfWGmq3pLSZdeGu0&system_capacity=4.08&module_type=0&losses=14.16&array_type=0&tilt=0.0&azimuth=180.00&lat=29.035&lon=48.14&dataset=intl&radius=0&timeframe=monthly&dc_ac_ratio=1.1&gcr=0.4&inv_eff=96

**Comment by reger** [comment]
@Juantxor I replied to your contact form inquiry.

**Comment by just-fo-sho** [comment]
Having the same issue here...
I can't figure out what exactly i'm doing wrong. 
I've made several calls with similarly structure API calls for other locations and it has worked: just doesn't work for this case. 

API call: "https://developer.nrel.gov/api/pvwatts/v5.xml?api_key=i7f73IZcUPetV8F7q7fUSHIehF7J1QwwIhah1H6b&lat=32.4725&lon=-99.5443&system_capacity=300000&azimuth=180&timeframe=hourly&array_type=0&tilt=40&module_type=0&losses=10&dataset=tmy3&radius=0"


<?xml version="1.0" encoding="UTF-8"?>
<response>
  <inputs>
    <lat>32.4725</lat>
    <lon>-99.5443</lon>
    <system-capacity>300000</system-capacity>
    <azimuth>180</azimuth>
    <timeframe>hourly</timeframe>
    <array-type>0</array-type>
    <tilt>40</tilt>
    <module-type>0</module-type>
    <losses>10</losses>
    <dataset>tmy3</dataset>
    <radius>0</radius>
  </inputs>
  <errors type="array">
    <error>An internal error occurred in the pvwattsv5 module.</error>
  </errors>
  <warnings type="array"/>
  <version>1.2.0</version>
  <ssc-info>
    <version type="integer">45</version>
    <build>Linux 64 bit GNU/C++ Jul  7 2015 14:24:09</build>
  </ssc-info>
  <outputs>
  </outputs>
</response>

**Comment by GUI** [comment]
I'm going to close this due to inactivity, but give a shout if anyone's still running into this.
