### ISSUE TITLE
Change in format for TMY temperature data?

### ISSUE THREAD

**Issue by craftj2** [NREL/developer.nrel.gov#220]
There appears to have been a change in format for the data. My API requests are now returning values for temperature in what I guess are 1/10ths of a degree C (i.e. 190 = 19.0 degrees C). I haven't been able to find any documentation of this change. is this accurate?

**Comment by jja262** [comment]
I also noticed this. I pulled PSM3 data for a few sites in the US, and it looks like the temperatures have all been multiplied by 10.

**Comment by chrisd31** [comment]
Here are minimal reproduction steps:

`https://developer.nrel.gov/api/nsrdb/v2/solar/psm3-tmy-download.csv?wkt=POINT(-115.0+36.0)&attributes=dhi%2Cdni%2Cghi%2Cdew_point%2Cair_temperature%2Csurface_pressure%2Cwind_direction%2Cwind_speed%2Csurface_albedo%2C%2C%2C&names=tmy&full_name=Louis%20Bourbon&email=sun.king@nrel.gov&affiliation=NREL&mailing_list=false&reason=test&utc=true&api_key=key`

The issue is happening in both columns: Dew Point, Temperature

**Comment by PjEdwards** [comment]
Let me take a look. We recently deployed the 2020 data. I'm guessing the scale factor meta is missing from the new file.

**Comment by PjEdwards** [comment]
OK, we have a data issue. Going to rollback 2020 for a couple of days until we get it fixed. Give it about 30 minutes for the deployment to propagate. Thanks for the heads up!

**Comment by chrisd31** [comment]
I can confirm that the reproduction steps above now return reasonable values for Dew Point and Temperature. Also returns:
* Location ID: 103426
* Version: 3.1.1
* tmy: 2019

Did the rollback happened for all locations or only 103426? Thanks

**Comment by PjEdwards** [comment]
Yep, all locations. The way this works is that if you request "tmy" instead of a specific year (e.g. "tmy-2019") you will get the most recent year. When the 2020 data came out I updated the "tmy" alias to point at 2020 instead of 2019. When this bug was reported I simply updated the alias to point back at 2019 data again. I think it's important to be aware that we do this so you can choose if you actually like using the alias (knowing that the data will change once a year), or if you'd prefer to simply use "tmy-2019" and explicitly update to 2020 when/if you decide to do so.

Also, sounds like one of our people in the delivery chain for this data is out next week. The 2020 TMY may not get fixed until week after next. I'll leave this ticket open until we deploy the fixed data and switch the "tmy" alias over to "tmy-2020".

Cheers!
Paul

**Comment by reger** [comment]
@PjEdwards let me know when you want this closed

**Comment by PjEdwards** [comment]
Yes! Can be closed. New data was rolled out last week. SOrry didn't update ticket sooner. Thanks Rob!
