### ISSUE TITLE
Utility rates API: Blank/null company ID

### ISSUE THREAD

**Issue by grimsa** [NREL/developer.nrel.gov#266]
We are looking at using Utility rates API (`GET /api/utility_rates/v3`) to determine the utility IDs of companies operating at a given location (lat/long).

In one case we observed the following response:
```
{
  "inputs": {
    "lat": "31.908",
    "lon": "-97.0524"
  },
  "errors": [],
  "warnings": [],
  "version": "3.1.0",
  "metadata": {
    "sources": [
      "Ventyx Research (2012)"
    ]
  },
  "outputs": {
    "company_id": "",
    "utility_name": "TXU Energy Retail Co LP",
    "utility_info": [
      {
        "company_id": null,
        "utility_name": "TXU Energy Retail Co LP"
      }
    ],
    "commercial": 0.0816,
    "industrial": 0.0557,
    "residential": 0.1098
  }
}
```

In this case the company ID is either blank (`""`) or `null`.

A quick Google search suggests
> TXU Energy Retail Co LP has utility ID #19327 and is located in Texas. [(source)](https://apps.openei.org/USURDB/?utilRateFinder=TXU%20Energy%20Retail%20Co%20LP)

Are `null` utility IDs expected in the dataset on which the NREL utility rates API is based, or is it a one-off data issue?

**Comment by reger** [comment]
@grimsa To be honest, I don't know. It's possible that at the time the data we built the API on did not have the ID for that company. Yes, not the most helpful answer, especially considering I'm the one who implemented the API in question, but there hasn't been any funding to maintain the API or update the data, so that's about all I have.

I would also like to point out that the data behind that API is from 2012. Far from being considered recent or up-to-date by most measures. I would suggest you look at the URDB on OpenEI for utility company and rate info. Details can be found at https://openei.org/wiki/Utility_Rate_Database, including an API.

**Comment by grimsa** [comment]
Thank you, this is helpful. We'll look into using OpenEI database instead.
