### ISSUE TITLE
PVWatts API doesn't return correct data for international locations that are very close to US border and for which the weather station happens to be in the US

### ISSUE THREAD

**Issue by nisaraf** [NREL/developer.nrel.gov#45]
I used the following URL to find station data for a location in Ciudad Juarez, Chihuahua, Mexico: 
http://developer.nrel.gov/api/pvwatts/v5.json?api_key=DEMO_KEY&lat=31.7219062&lon=-106.4040952&system_capacity=4&azimuth=180&tilt=40&array_type=1&module_type=1&losses=10&dataset=intl

In response, I got an error (422) suggesting that "No climate data found with dataset=intl for location specified: lat=31.7219062 lon=-106.4040952"

The problem here is that Cd Juarez is very close to the US border and the closest station happens to be in El Paso, TX, which is NOT an international location from US' perspective, therefore dataset=intl returns an error.

Note that invoking the same URL without dataset param altogether OR with dataset=tmy2 OR dataset=tmy3 does return a result and not an error.

Ideally, should not the API take care of returning an appropriate result in scenarios wherein the "international" location is typically served by a "domestic" station?

**Comment by reger** [comment]
Right now the PVWatts API treats the various datasets as completely separate. So when you pass in `dataset=intl` we only look at stations in that dataset. It would be confusing if you passed in `dataset=intl` and then pvwatts gave you results using tmy2.

The reason you get a result when you don't send in the dataset param is that it uses tmy2 as the default, which I'm guessing

**Comment by nisaraf** [comment]
Yes, it's tmy2 that is being returned as default, when dataset param is not sent in the request.

Another example: For a location in Dawson, Canada (48.8035835,-94.6208837), the URL with `dataset=intl ` returns the same error; though with `dataset=tmy3`, city=BAUDETTE INTERNATIONAL is returned. I noticed how `dataset=tmy3` in case of Cd Juarez (Mexico) returns city=EL PASO INTERNATIONAL AP. Notice the **International** in both of these cases?

Can the PVWatts API take care of this special scenario and return appropriate data; may be the default data?

**Comment by reger** [comment]
The "International" in those examples is just part of the name of the station, not an indication of what dataset the station is part of. The name of the field being "city" can be a bit confusing in some cases since it's the station name and not always the city name, but that's how pvwatts has always returned it. 

If you specify tmy2 or tmy3 for those examples you get results because there are stations within the default radius (50 miles) within those datasets. There are no stations in the intl dataset within that radius of those locations.

You can use the Solar Dataset Query API to see what stations are closest, within a certain radius, etc across all the available datasets.  https://developer.nrel.gov/docs/solar/data-query-v1/

Are you saying you think the API should use tmy2 data even if the request specified tmy3 or intl as the dataset, if there is no data in the specified dataset? I'm not sure exactly what you feel the behavior should be.

**Comment by nisaraf** [comment]
Agree that there are no stations in intl dataset within the default radius of these locations, but I also noticed that even if the radius is set to maximum possible, it still doesn't return any intl stations for these locations, because there's no such station.

I was just thinking out loud: When the location is international but no corresponding international station is found, then probably return the closest non-intl station?

**Comment by reger** [comment]
If you pass in `radius=0` along with `dataset=intl` it should use the closest station in that dataset, regardless of distance. For some reason it's not doing that for the Ciudad Juarez example in your initial post. Interestingly it seems to work for other locations, both inside and outside the US, including your Dawson, Canada example. 

I figured out the problem, luckily it wasn't anything major, just something in one of our database tables where we do lookups for the international stations. The Ciudad Juarez example should be working correctly now if you pass in `radius=0`, using the Mexico City station from the `intl` dataset. Thanks for bringing this up.
