### ISSUE TITLE
Error HTTP: 429

### ISSUE THREAD

**Issue by sergiocastellanos** [NREL/developer.nrel.gov#51]
I keep getting Error HTTP: 429 when using python's API (following your guidelines on https://nsrdb.nrel.gov/api-instructions). I've been using a sleep timer between requests of 3.7 seconds to prevent violating the hourly limit of 1,000 requests per hour. However, after 40-50 iterations of coordinate positions, I get error HTTP: 429. Could you please let me know why is this happening?

**Comment by GUI** [comment]
@sergiocastellanos: The rate limits for this API are actually lower than our defaults: http://developer.nrel.gov/docs/solar/nsrdb/psm_data_download/#rate-limits Although, I believe that documentation is out of date and the rate limit is now 50 requests per hour and 100 requests per day.

@PjEdwards: If I'm reading the admin correctly, I believe the limits are 100 per day now, instead of the documented 100 per hour. If that's correct, should we updated the docs? Do you also know anything about the [nsrdb docs](https://nsrdb.nrel.gov/api-instructions) demonstrating this API? If so, do you think the rate limits are worth mentioning there too?

**Comment by PjEdwards** [comment]
Yes, those docs _are_ incorrect. I will update them immediately. We are actually bumping the limit up to 200 a day. I will modify both the docs and the configuration accordingly. I don't control that NSRDB site but I can recommend that they add something about the rate limits there. I agree that it would be a good thing to clarify.

**Comment by GUI** [comment]
Thanks, @PjEdwards! @sergiocastellanos: We've updated the [api documentation](http://developer.nrel.gov/docs/solar/nsrdb/psm_data_download/#rate-limits). Thanks for pointing this out, but sorry for any confusion! Feel free to reach out if you have any other questions.
