### ISSUE TITLE
Request rejected? (again)

### ISSUE THREAD

**Issue by craftj2** [NREL/developer.nrel.gov#96]
This is a follow up to Issue #90

https://github.com/NREL/developer.nrel.gov/issues/90

The same error is occurring again after 2 months of operational bliss. Here is the specific response I get this time:

Request Rejected

An error has occurred. Please consult with your administrator.

Your support ID is: 9946171700951584224

**Comment by GUI** [comment]
@PjEdwards: Looping you in here. I filed a ticket with ITS, but it sounds like this support ID is masking a 504 gateway timeout issue. So are there any known timeout issues with the NSRDB API?

**Comment by PjEdwards** [comment]
Yes, unfortunately these APIs are serving massive datasets on servers with fairly limited hardware resources. Occasionally during times of peak load we will see a greater density of intermittent timeouts. This primarily impacts requests using the `CSV` format since these requests need to start streaming data in 30 seconds or a timeout occurs. If you're seeing timeouts on a `JSON` format request then something bad is happening that I should look into. @craftj2 are you seeing timeouts still today? If so, are they on `CSV` requests or `JSON` requests?

**Comment by craftj2** [comment]
The requests are working again, I am using the json format for my requests

**Comment by pfairey** [comment]
I am receiving the following error when trying to access https://www.nrel.gov
An error has occurred. Please consult with your administrator.
Your support ID is: 8485505872547637387

**Comment by GUI** [comment]
@pfairey: Can you tell us which specific API URL you're hitting? Thanks!

**Comment by pfairey** [comment]
No API of which I am aware. I get this response from entering www.nrel.gov in my Firefox browser.

Philip Fairey
Sent from my iPhone
(o) 321-638-1005
(c) 321-537-6233

**Comment by pfairey** [comment]
Could have been some kind of API that Google used to attempt to direct me to a document I wanted to view that is likely on NREL's publication database. I assume that is a possibility but then I was unable to get to the main NREL URL.
